LIST_OF_EXPERIMENTS_FILTERED_WITH_TWO_PROJECTS = {
    "data": [
        {
            "data": [
                {
                    "dtCreated": "2019-03-21T08:48:49.449397+00:00",
                    "dtDeleted": None,
                    "dtFinished": None,
                    "dtModified": "2019-03-21T08:48:49.449397+00:00",
                    "dtProvisioningFinished": None,
                    "dtProvisioningStarted": None,
                    "dtStarted": None,
                    "dtTeardownFinished": None,
                    "dtTeardownStarted": None,
                    "experimentError": "Expecting value: line 1 column 1 (char 0)",
                    "experimentTemplateHistoryId": 297,
                    "experimentTemplateId": 8,
                    "experimentTypeId": 1,
                    "handle": "esj8mcpaayh5kx",
                    "id": 295,
                    "projectHandle": "pr4yxj956",
                    "projectId": 14898,
                    "started_by_user_id": 1,
                    "state": 7,
                    "templateHistory": {
                        "dtCreated": "2019-03-21T08:48:48.436994+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 8,
                        "id": 297,
                        "params": {
                            "artifactDirectory": "sagdf",
                            "clusterId": 342,
                            "experimentEnv": {
                                "k": "v"
                            },
                            "experimentTypeId": 1,
                            "name": "dsfads",
                            "ports": 3245,
                            "project_handle": "pr4yxj956",
                            "worker_command": "sadas",
                            "worker_container": "asd",
                            "worker_machine_type": "C2",
                            "workingDirectory": "sadfas",
                            "workspaceUrl": "sadfds"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-21T08:48:29.553574+00:00",
                    "dtDeleted": None,
                    "dtFinished": None,
                    "dtModified": "2019-03-21T08:48:29.553574+00:00",
                    "dtProvisioningFinished": None,
                    "dtProvisioningStarted": None,
                    "dtStarted": None,
                    "dtTeardownFinished": None,
                    "dtTeardownStarted": None,
                    "experimentError": "{'name': 'Error', 'status': 400, 'message': 'Invalid machine type'}",
                    "experimentTemplateHistoryId": 296,
                    "experimentTemplateId": 8,
                    "experimentTypeId": 1,
                    "handle": "estun7jhqta8sm",
                    "id": 294,
                    "projectHandle": "pr4yxj956",
                    "projectId": 14898,
                    "started_by_user_id": 1,
                    "state": 7,
                    "templateHistory": {
                        "dtCreated": "2019-03-21T08:48:28.467167+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 8,
                        "id": 296,
                        "params": {
                            "artifactDirectory": "sagdf",
                            "clusterId": 342,
                            "experimentEnv": {
                                "k": "v"
                            },
                            "experimentTypeId": 1,
                            "name": "dsfads",
                            "ports": 3245,
                            "project_handle": "pr4yxj956",
                            "worker_command": "sadas",
                            "worker_container": "asd",
                            "worker_machine_type": "c2",
                            "workingDirectory": "sadfas",
                            "workspaceUrl": "sadfds"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-21T08:44:42.581919+00:00",
                    "dtDeleted": None,
                    "dtFinished": None,
                    "dtModified": "2019-03-21T08:44:42.581919+00:00",
                    "dtProvisioningFinished": None,
                    "dtProvisioningStarted": None,
                    "dtStarted": None,
                    "dtTeardownFinished": None,
                    "dtTeardownStarted": None,
                    "experimentError": "{'name': 'Error', 'status': 400, 'message': 'Invalid machine type'}",
                    "experimentTemplateHistoryId": 295,
                    "experimentTemplateId": 8,
                    "experimentTypeId": 1,
                    "handle": "es08mwh7ye6zpm",
                    "id": 293,
                    "projectHandle": "pr4yxj956",
                    "projectId": 14898,
                    "started_by_user_id": 1,
                    "state": 7,
                    "templateHistory": {
                        "dtCreated": "2019-03-21T08:44:41.366528+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 8,
                        "id": 295,
                        "params": {
                            "artifactDirectory": "sagdf",
                            "clusterId": 342,
                            "experimentEnv": {
                                "k": "v"
                            },
                            "experimentTypeId": 1,
                            "name": "dsfads",
                            "ports": 3245,
                            "project_handle": "pr4yxj956",
                            "worker_command": "sadas",
                            "worker_container": "asd",
                            "worker_machine_type": "sadas",
                            "workingDirectory": "sadfas",
                            "workspaceUrl": "sadfds"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-19T16:35:28.425184+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-19T16:38:40.664560+00:00",
                    "dtModified": "2019-03-19T16:35:28.425184+00:00",
                    "dtProvisioningFinished": "2019-03-19T16:37:37.516138+00:00",
                    "dtProvisioningStarted": "2019-03-19T16:37:37.516138+00:00",
                    "dtStarted": "2019-03-19T16:37:37.516138+00:00",
                    "dtTeardownFinished": "2019-03-19T16:38:40.664560+00:00",
                    "dtTeardownStarted": "2019-03-19T16:38:40.664560+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 38,
                    "experimentTemplateId": 8,
                    "experimentTypeId": 1,
                    "handle": "eshdufkt9ti8mx",
                    "id": 38,
                    "projectHandle": "pr4yxj956",
                    "projectId": 14898,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-19T16:35:28.425184+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 8,
                        "id": 38,
                        "params": {
                            "command": "python2 hello.py",
                            "container": "paperspace/tensorflow-python",
                            "project": "paperspace-python",
                            "workspaceFileName": "hello.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-19T14:52:42.476592+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-19T14:53:00.850701+00:00",
                    "dtModified": "2019-03-19T14:52:42.476592+00:00",
                    "dtProvisioningFinished": "2019-03-19T14:52:46.844619+00:00",
                    "dtProvisioningStarted": "2019-03-19T14:52:46.844619+00:00",
                    "dtStarted": "2019-03-19T14:52:46.844619+00:00",
                    "dtTeardownFinished": "2019-03-19T14:53:00.850701+00:00",
                    "dtTeardownStarted": "2019-03-19T14:53:00.850701+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 34,
                    "experimentTemplateId": 8,
                    "experimentTypeId": 1,
                    "handle": "e07h0ym8fewm",
                    "id": 34,
                    "projectHandle": "pr4yxj956",
                    "projectId": 14898,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-19T14:52:42.476592+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 8,
                        "id": 34,
                        "params": {
                            "command": "python2 hello.py",
                            "container": "paperspace/tensorflow-python",
                            "project": "paperspace-python",
                            "workspaceFileName": "hello.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-19T14:46:21.605202+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-19T14:46:40.360111+00:00",
                    "dtModified": "2019-03-19T14:46:21.605202+00:00",
                    "dtProvisioningFinished": "2019-03-19T14:46:26.094384+00:00",
                    "dtProvisioningStarted": "2019-03-19T14:46:26.094384+00:00",
                    "dtStarted": "2019-03-19T14:46:26.094384+00:00",
                    "dtTeardownFinished": "2019-03-19T14:46:40.360111+00:00",
                    "dtTeardownStarted": "2019-03-19T14:46:40.360111+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 33,
                    "experimentTemplateId": 8,
                    "experimentTypeId": 1,
                    "handle": "e0fq31vyla039",
                    "id": 33,
                    "projectHandle": "pr4yxj956",
                    "projectId": 14898,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-19T14:46:21.605202+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 8,
                        "id": 33,
                        "params": {
                            "command": "python3 hello.py",
                            "container": "paperspace/tensorflow-python",
                            "project": "paperspace-python",
                            "workspaceFileName": "hello.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-19T14:38:38.227536+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-19T14:42:41.723400+00:00",
                    "dtModified": "2019-03-19T14:38:38.227536+00:00",
                    "dtProvisioningFinished": "2019-03-19T14:41:34.630690+00:00",
                    "dtProvisioningStarted": "2019-03-19T14:41:34.630690+00:00",
                    "dtStarted": "2019-03-19T14:41:34.630690+00:00",
                    "dtTeardownFinished": "2019-03-19T14:42:41.723400+00:00",
                    "dtTeardownStarted": "2019-03-19T14:42:41.723400+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 32,
                    "experimentTemplateId": 8,
                    "experimentTypeId": 1,
                    "handle": "esxz3ihfl9qxs2",
                    "id": 32,
                    "projectHandle": "pr4yxj956",
                    "projectId": 14898,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-19T14:38:38.227536+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 8,
                        "id": 32,
                        "params": {
                            "command": "python3 hello.py",
                            "container": "paperspace/tensorflow-python",
                            "project": "paperspace-python",
                            "workspaceFileName": "hello.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-14T14:06:27.383232+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-14T14:10:05.315380+00:00",
                    "dtModified": "2019-03-14T14:06:27.383232+00:00",
                    "dtProvisioningFinished": "2019-03-14T14:10:00.097887+00:00",
                    "dtProvisioningStarted": "2019-03-14T14:09:02.736309+00:00",
                    "dtStarted": "2019-03-14T14:10:00.097887+00:00",
                    "dtTeardownFinished": "2019-03-14T14:10:05.809122+00:00",
                    "dtTeardownStarted": "2019-03-14T14:10:05.462304+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 32862,
                    "experimentTemplateId": 8,
                    "experimentTypeId": 1,
                    "handle": "ecqq0rz0gok9i",
                    "id": 32860,
                    "projectHandle": "pr4yxj956",
                    "projectId": 14898,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-22T23:31:15.372159+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 8,
                        "id": 32862,
                        "params": {
                            "clusterId": "clmtkpnm2",
                            "command": "python3 hello.py",
                            "containerUrl": "paperspace/tensorflow-python",
                            "isPreemptible": False,
                            "machineType": "K80",
                            "name": "job 5",
                            "projectId": "pr4yxj956",
                            "startedByUserId": "u3z4be26",
                            "workspaceUrl": "s3://ps-projects/pr4yxj956/jw276004uoaiv/hello.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-14T11:22:14.345466+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-14T11:23:17.763554+00:00",
                    "dtModified": "2019-03-14T11:22:14.345466+00:00",
                    "dtProvisioningFinished": "2019-03-14T11:23:12.549387+00:00",
                    "dtProvisioningStarted": "2019-03-14T11:22:18.820247+00:00",
                    "dtStarted": "2019-03-14T11:23:12.549387+00:00",
                    "dtTeardownFinished": "2019-03-14T11:23:18.063367+00:00",
                    "dtTeardownStarted": "2019-03-14T11:23:17.900575+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 32859,
                    "experimentTemplateId": 8,
                    "experimentTypeId": 1,
                    "handle": "es310784c1o1x6",
                    "id": 32857,
                    "projectHandle": "pr4yxj956",
                    "projectId": 14898,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-22T23:31:15.372159+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 8,
                        "id": 32859,
                        "params": {
                            "clusterId": "clmtkpnm2",
                            "command": "python3 hello.py",
                            "containerUrl": "paperspace/tensorflow-python",
                            "isPreemptible": False,
                            "machineType": "K80",
                            "name": "job 4",
                            "projectId": "pr4yxj956",
                            "startedByUserId": "u3z4be26",
                            "workspaceUrl": "s3://ps-projects/pr4yxj956/jpngp435ekbp9/hello.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-09T11:05:34.409959+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-09T11:09:38.903533+00:00",
                    "dtModified": "2019-03-09T11:05:34.409959+00:00",
                    "dtProvisioningFinished": "2019-03-09T11:09:33.686660+00:00",
                    "dtProvisioningStarted": "2019-03-09T11:08:34.681334+00:00",
                    "dtStarted": "2019-03-09T11:09:33.686660+00:00",
                    "dtTeardownFinished": "2019-03-09T11:09:39.194718+00:00",
                    "dtTeardownStarted": "2019-03-09T11:09:39.036278+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 32351,
                    "experimentTemplateId": 8,
                    "experimentTypeId": 1,
                    "handle": "esabwtehoekn6w",
                    "id": 32349,
                    "projectHandle": "pr4yxj956",
                    "projectId": 14898,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-22T23:31:15.372159+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 8,
                        "id": 32351,
                        "params": {
                            "clusterId": "clmtkpnm2",
                            "command": "python3 hello.py",
                            "containerUrl": "paperspace/tensorflow-python",
                            "isPreemptible": False,
                            "machineType": "K80",
                            "name": "job 3",
                            "projectId": "pr4yxj956",
                            "startedByUserId": "u3z4be26",
                            "workspaceUrl": "s3://ps-projects/pr4yxj956/jafb4f2w30afo/hello.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-06T13:56:55.165302+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-06T13:57:13.165854+00:00",
                    "dtModified": "2019-03-06T13:56:55.165302+00:00",
                    "dtProvisioningFinished": "2019-03-06T13:57:07.955608+00:00",
                    "dtProvisioningStarted": "2019-03-06T13:57:00.905506+00:00",
                    "dtStarted": "2019-03-06T13:57:07.955608+00:00",
                    "dtTeardownFinished": "2019-03-06T13:57:13.454509+00:00",
                    "dtTeardownStarted": "2019-03-06T13:57:13.299681+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 31991,
                    "experimentTemplateId": 8,
                    "experimentTypeId": 1,
                    "handle": "ea1d6t082wq7i",
                    "id": 31989,
                    "projectHandle": "pr4yxj956",
                    "projectId": 14898,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-22T23:31:15.372159+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 8,
                        "id": 31991,
                        "params": {
                            "clusterId": "clmtkpnm2",
                            "command": "python3 hello.py",
                            "containerUrl": "paperspace/tensorflow-python",
                            "isPreemptible": False,
                            "machineType": "K80",
                            "name": "job 2",
                            "projectId": "pr4yxj956",
                            "startedByUserId": "u3z4be26",
                            "workspaceUrl": "s3://ps-projects/pr4yxj956/jst4l3hoi0hcyn/hello.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-06T13:52:48.106674+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-06T13:56:29.890444+00:00",
                    "dtModified": "2019-03-06T13:52:48.106674+00:00",
                    "dtProvisioningFinished": "2019-03-06T13:56:24.678388+00:00",
                    "dtProvisioningStarted": "2019-03-06T13:55:32.325678+00:00",
                    "dtStarted": "2019-03-06T13:56:24.678388+00:00",
                    "dtTeardownFinished": "2019-03-06T13:56:30.178571+00:00",
                    "dtTeardownStarted": "2019-03-06T13:56:30.024471+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 31989,
                    "experimentTemplateId": 8,
                    "experimentTypeId": 1,
                    "handle": "esbipxwngbmji4",
                    "id": 31987,
                    "projectHandle": "pr4yxj956",
                    "projectId": 14898,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-22T23:31:15.372159+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 8,
                        "id": 31989,
                        "params": {
                            "clusterId": "clmtkpnm2",
                            "command": "python3 hello.py",
                            "containerUrl": "paperspace/tensorflow-python",
                            "isPreemptible": False,
                            "machineType": "K80",
                            "name": "job 1",
                            "projectId": "pr4yxj956",
                            "startedByUserId": "u3z4be26",
                            "workspaceUrl": "s3://ps-projects/pr4yxj956/j5cidd1koia24/hello.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                }
            ],
            "meta": {
                "itemGroup": {
                    "key": "projectHandle",
                    "value": "pr4yxj956"
                },
                "totalItems": 12
            }
        },
        {
            "data": [
                {
                    "dtCreated": "2019-03-25T14:35:05.738112+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-25T14:35:21.314193+00:00",
                    "dtModified": "2019-03-25T14:35:05.738112+00:00",
                    "dtProvisioningFinished": "2019-03-25T14:35:12.777000+00:00",
                    "dtProvisioningStarted": "2019-03-25T14:35:12.777000+00:00",
                    "dtStarted": "2019-03-25T14:35:12.777000+00:00",
                    "dtTeardownFinished": "2019-03-25T14:35:21.314193+00:00",
                    "dtTeardownStarted": "2019-03-25T14:35:21.314193+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 33353,
                    "experimentTemplateId": 2257,
                    "experimentTypeId": 1,
                    "handle": "e8lufvr2bh8ld",
                    "id": 33351,
                    "projectHandle": "pr1opq9uz",
                    "projectId": 15548,
                    "started_by_user_id": 199654,
                    "state": 7,
                    "templateHistory": {
                        "dtCreated": "2019-03-25T14:35:05.738112+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 2257,
                        "id": 33353,
                        "params": {
                            "command": "nvidia-smi",
                            "container": "Test-Container",
                            "isPreemptible": False,
                            "machineType": "C2",
                            "projectId": "pr1opq9uz",
                            "workspaceFileName": "none"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-25T14:20:07.758313+00:00",
                    "dtDeleted": None,
                    "dtFinished": None,
                    "dtModified": "2019-03-25T14:20:07.758313+00:00",
                    "dtProvisioningFinished": None,
                    "dtProvisioningStarted": None,
                    "dtStarted": None,
                    "dtTeardownFinished": None,
                    "dtTeardownStarted": None,
                    "experimentError": "Expecting value: line 1 column 1 (char 0)",
                    "experimentTemplateHistoryId": 33352,
                    "experimentTemplateId": 2257,
                    "experimentTypeId": 1,
                    "handle": "esasysj42i2j2s",
                    "id": 33350,
                    "projectHandle": "pr1opq9uz",
                    "projectId": 15548,
                    "started_by_user_id": 199654,
                    "state": 7,
                    "templateHistory": {
                        "dtCreated": "2019-03-25T14:20:06.517435+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 2257,
                        "id": 33352,
                        "params": {
                            "experimentTypeId": 1,
                            "name": "dsfads",
                            "ports": 5000,
                            "project_handle": "pr1opq9uz",
                            "worker_command": "sadas",
                            "worker_container": "asd",
                            "worker_machine_type": "C2"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-15T11:46:32.978544+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-15T11:46:50.541797+00:00",
                    "dtModified": "2019-03-15T11:46:32.978544+00:00",
                    "dtProvisioningFinished": "2019-03-15T11:46:45.501290+00:00",
                    "dtProvisioningStarted": "2019-03-15T11:46:41.431717+00:00",
                    "dtStarted": "2019-03-15T11:46:45.501290+00:00",
                    "dtTeardownFinished": "2019-03-15T11:46:50.598748+00:00",
                    "dtTeardownStarted": "2019-03-15T11:46:50.561267+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 32879,
                    "experimentTemplateId": 2257,
                    "experimentTypeId": 1,
                    "handle": "estgm33hfbqf5k",
                    "id": 32877,
                    "projectHandle": "pr1opq9uz",
                    "projectId": 15548,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-22T23:31:15.372159+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 2257,
                        "id": 32879,
                        "params": {
                            "clusterId": "cls28l0qm",
                            "command": "python3 myscript.py",
                            "containerUrl": "paperspace/tensorflow-python",
                            "isPreemptible": False,
                            "machineType": "P5000",
                            "name": "job 4",
                            "projectId": "pr1opq9uz",
                            "startedByUserId": "u3z4be26",
                            "workspaceUrl": "s3://ps-projects/pr1opq9uz/j8bxv3ni2zc17/myscript.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-15T11:46:32.513024+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-15T11:46:50.363855+00:00",
                    "dtModified": "2019-03-15T11:46:32.513024+00:00",
                    "dtProvisioningFinished": "2019-03-15T11:46:45.324783+00:00",
                    "dtProvisioningStarted": "2019-03-15T11:46:40.947880+00:00",
                    "dtStarted": "2019-03-15T11:46:45.324783+00:00",
                    "dtTeardownFinished": "2019-03-15T11:46:50.419813+00:00",
                    "dtTeardownStarted": "2019-03-15T11:46:50.383192+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 32878,
                    "experimentTemplateId": 2257,
                    "experimentTypeId": 1,
                    "handle": "esbo3pisqq3t68",
                    "id": 32876,
                    "projectHandle": "pr1opq9uz",
                    "projectId": 15548,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-22T23:31:15.372159+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 2257,
                        "id": 32878,
                        "params": {
                            "clusterId": "cls28l0qm",
                            "command": "python3 myscript.py",
                            "containerUrl": "paperspace/tensorflow-python",
                            "isPreemptible": False,
                            "machineType": "P5000",
                            "name": "job 3",
                            "projectId": "pr1opq9uz",
                            "startedByUserId": "u3z4be26",
                            "workspaceUrl": "s3://ps-projects/pr1opq9uz/jpk82qnq71w9c/myscript.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-15T11:46:16.422317+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-15T11:46:30.820071+00:00",
                    "dtModified": "2019-03-15T11:46:16.422317+00:00",
                    "dtProvisioningFinished": "2019-03-15T11:46:25.776927+00:00",
                    "dtProvisioningStarted": "2019-03-15T11:46:21.616491+00:00",
                    "dtStarted": "2019-03-15T11:46:25.776927+00:00",
                    "dtTeardownFinished": "2019-03-15T11:46:30.873777+00:00",
                    "dtTeardownStarted": "2019-03-15T11:46:30.839238+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 32877,
                    "experimentTemplateId": 2257,
                    "experimentTypeId": 1,
                    "handle": "eso8s7e014681",
                    "id": 32875,
                    "projectHandle": "pr1opq9uz",
                    "projectId": 15548,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-22T23:31:15.372159+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 2257,
                        "id": 32877,
                        "params": {
                            "clusterId": "cls28l0qm",
                            "command": "python3 test_remote.py",
                            "containerUrl": "paperspace/tensorflow-python",
                            "isPreemptible": False,
                            "machineType": "P5000",
                            "name": "job 2",
                            "projectId": "pr1opq9uz",
                            "startedByUserId": "u3z4be26",
                            "workspaceUrl": "s3://ps-projects/pr1opq9uz/jsuqgzne50tlg1/test_remote.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                },
                {
                    "dtCreated": "2019-03-15T11:26:14.607276+00:00",
                    "dtDeleted": None,
                    "dtFinished": "2019-03-15T11:26:32.872835+00:00",
                    "dtModified": "2019-03-15T11:26:14.607276+00:00",
                    "dtProvisioningFinished": "2019-03-15T11:26:27.823314+00:00",
                    "dtProvisioningStarted": "2019-03-15T11:26:23.367983+00:00",
                    "dtStarted": "2019-03-15T11:26:27.823314+00:00",
                    "dtTeardownFinished": "2019-03-15T11:26:32.930538+00:00",
                    "dtTeardownStarted": "2019-03-15T11:26:32.897522+00:00",
                    "experimentError": None,
                    "experimentTemplateHistoryId": 32876,
                    "experimentTemplateId": 2257,
                    "experimentTypeId": 1,
                    "handle": "esml2ioetny5o6",
                    "id": 32874,
                    "projectHandle": "pr1opq9uz",
                    "projectId": 15548,
                    "started_by_user_id": 199654,
                    "state": 5,
                    "templateHistory": {
                        "dtCreated": "2019-03-22T23:31:15.372159+00:00",
                        "dtDeleted": None,
                        "experimentTemplateId": 2257,
                        "id": 32876,
                        "params": {
                            "clusterId": "cls28l0qm",
                            "command": "python3 myscript.py",
                            "containerUrl": "paperspace/tensorflow-python",
                            "isPreemptible": False,
                            "machineType": "P5000",
                            "name": "job 1",
                            "projectId": "pr1opq9uz",
                            "startedByUserId": "u3z4be26",
                            "workspaceUrl": "s3://ps-projects/pr1opq9uz/jsnze3m7s2xlpr/myscript.py.zip"
                        },
                        "triggerEvent": None,
                        "triggerEventId": None
                    }
                }
            ],
            "meta": {
                "itemGroup": {
                    "key": "projectHandle",
                    "value": "pr1opq9uz"
                },
                "totalItems": 6
            }
        }
    ],
    "message": "success",
    "meta": {
        "filter": [],
        "limit": 1000000,
        "offset": 0,
        "totalItems": 18
    }
}

LIST_OF_EXPERIMENTS_FILTERED_WITH_TWO_PROJECTS_STDOUT = """+--------+----------------+---------+
| Name   | Handle         | Status  |
+--------+----------------+---------+
| dsfads | esj8mcpaayh5kx | failed  |
| dsfads | estun7jhqta8sm | failed  |
| dsfads | es08mwh7ye6zpm | failed  |
| None   | eshdufkt9ti8mx | stopped |
| None   | e07h0ym8fewm   | stopped |
| None   | e0fq31vyla039  | stopped |
| None   | esxz3ihfl9qxs2 | stopped |
| job 5  | ecqq0rz0gok9i  | stopped |
| job 4  | es310784c1o1x6 | stopped |
| job 3  | esabwtehoekn6w | stopped |
| job 2  | ea1d6t082wq7i  | stopped |
| job 1  | esbipxwngbmji4 | stopped |
| None   | e8lufvr2bh8ld  | failed  |
| dsfads | esasysj42i2j2s | failed  |
| job 4  | estgm33hfbqf5k | stopped |
| job 3  | esbo3pisqq3t68 | stopped |
| job 2  | eso8s7e014681  | stopped |
| job 1  | esml2ioetny5o6 | stopped |
+--------+----------------+---------+
"""

LIST_OF_EXPERIMENTS_FILTERED_BUT_NONE_FOUND = {
    "data": [
        {
            "data": [],
            "meta": {
                "itemGroup": {
                    "key": "projectHandle",
                    "value": "pr4yxj95"
                },
                "totalItems": 0
            }
        },
        {
            "data": [],
            "meta": {
                "itemGroup": {
                    "key": "projectHandle",
                    "value": "pr1opq9u"
                },
                "totalItems": 0
            }
        }
    ],
    "message": "success",
    "meta": {
        "filter": [],
        "limit": 1000000,
        "offset": 0,
        "totalItems": 0
    }
}

CREATE_DEPLOYMENT_WITH_BASIC_OPTIONS_RESPONSE = {
    "deployment": {
        "id": "sadkfhlskdjh",
        "ownerId": "tejxgn5bt",
        "projectId": "prmr22ve0",
        "experimentId": "ehla1kvbwzaco",
        "state": "Stopped",
        "startedByUserId": "ukgvw4i8",
        "startedByUserEmail": "batman.bin.supraman@paperspace.com",
        "deploymentType": "Tensorflow Serving on K8s",
        "modelId": "mosu30xm7q8vb0p",
        "modelUrl": "s3://ps-projects-development/prmr22ve0/ehla1kvbwzaco/model/",
        "name": "some_name",
        "tag": None,
        "params": None,
        "code": None,
        "cluster": "PS Jobs on GCP",
        "machineType": "K80",
        "imageUrl": "https://www.latlmes.com/breaking/paperspace-now-has-a-100-bilion-valuation",
        "imageUsername": None,
        "imagePassword": None,
        "workspaceUrl": None,
        "workspaceUsername": None,
        "workspacePassword": None,
        "instanceCount": 1,
        "runningCount": 0,
        "error": None,
        "authToken": "-----",
        "annotations": {},
        "oauthKey": "-----",
        "oauthSecret": "some_oauth_secret",
        "serviceType": "model",
        "apiType": "REST",
        "endpoint": "https://development-services.paperspace.io/model-serving/desanw1jptk7woh:predict",
        "ports": None,
        "dtCreated": "2019-04-04T10:27:22.659Z",
        "dtModified": "2019-04-04T10:27:22.659Z",
        "dtBuildStarted": None,
        "dtBuildFinished": None,
        "dtProvisioningStarted": None,
        "dtProvisioningFinished": None,
        "dtStarted": None,
        "dtTeardownStarted": None,
        "dtTeardownFinished": None,
        "dtStopped": None,
        "dtDeleted": None,
        "isDeleted": False
    }
}

LIST_DEPLOYMENTS = {
    "deploymentList": [
        {
            "id": "dev61ity7lx232",
            "ownerId": "tejxgn5bt",
            "projectId": "prmr22ve0",
            "experimentId": "ehla1kvbwzaco",
            "state": "Stopped",
            "startedByUserId": "ukgvw4i8",
            "startedByUserEmail": "bartosz@paperspace.com",
            "deploymentType": "Tensorflow Serving on K8s",
            "modelId": "mosu30xm7q8vb0p",
            "modelUrl": "s3://ps-projects-development/prmr22ve0/ehla1kvbwzaco/model/",
            "name": "some_name",
            "tag": "some_tag",
            "params": None,
            "code": "some_code",
            "cluster": "PS Jobs on GCP",
            "machineType": "K80",
            "imageUrl": "https://github.com/Paperspace/mnist-sample",
            "imageUsername": "some_username",
            "imagePassword": "some_password",
            "workspaceUrl": "https://www.example.com",
            "workspaceUsername": "some_username",
            "workspacePassword": "some_password",
            "instanceCount": 1,
            "runningCount": 0,
            "error": None,
            "authToken": "some_auth_token",
            "annotations": {},
            "oauthKey": "some_oauth_key",
            "oauthSecret": "some_oauth_secret",
            "serviceType": "some_service_type",
            "apiType": "some_api_type",
            "endpoint": "https://development-services.paperspace.io/model-serving/dev61ity7lx232:predict",
            "ports": "5000",
            "dtCreated": "2019-04-04T10:53:56.665Z",
            "dtModified": "2019-04-04T10:53:56.729Z",
            "dtBuildStarted": None,
            "dtBuildFinished": None,
            "dtProvisioningStarted": None,
            "dtProvisioningFinished": None,
            "dtStarted": None,
            "dtTeardownStarted": None,
            "dtTeardownFinished": None,
            "dtStopped": "2019-04-04T10:53:56.711Z",
            "dtDeleted": None,
            "isDeleted": False
        },
        {
            "id": "desanw1jptk7woh",
            "ownerId": "tejxgn5bt",
            "projectId": "prmr22ve0",
            "experimentId": "ehla1kvbwzaco",
            "state": "Stopped",
            "startedByUserId": "ukgvw4i8",
            "startedByUserEmail": "bartosz@paperspace.com",
            "deploymentType": "Tensorflow Serving on K8s",
            "modelId": "mosu30xm7q8vb0p",
            "modelUrl": "s3://ps-projects-development/prmr22ve0/ehla1kvbwzaco/model/",
            "name": "some_name",
            "tag": None,
            "params": None,
            "code": None,
            "cluster": "PS Jobs on GCP",
            "machineType": "K80",
            "imageUrl": "https://github.com/Paperspace/mnist-sample",
            "imageUsername": None,
            "imagePassword": None,
            "workspaceUrl": None,
            "workspaceUsername": None,
            "workspacePassword": None,
            "instanceCount": 1,
            "runningCount": 0,
            "error": None,
            "authToken": "-----",
            "annotations": {},
            "oauthKey": "-----",
            "oauthSecret": "-----",
            "serviceType": "model",
            "apiType": "REST",
            "endpoint": "https://development-services.paperspace.io/model-serving/desanw1jptk7woh:predict",
            "ports": None,
            "dtCreated": "2019-04-04T10:27:22.659Z",
            "dtModified": "2019-04-04T10:27:22.726Z",
            "dtBuildStarted": None,
            "dtBuildFinished": None,
            "dtProvisioningStarted": None,
            "dtProvisioningFinished": None,
            "dtStarted": None,
            "dtTeardownStarted": None,
            "dtTeardownFinished": None,
            "dtStopped": "2019-04-04T10:27:22.710Z",
            "dtDeleted": None,
            "isDeleted": False
        },
        {
            "id": "desfnnrqt1v633v",
            "ownerId": "tejxgn5bt",
            "projectId": "prmr22ve0",
            "experimentId": "ehla1kvbwzaco",
            "state": "Stopped",
            "startedByUserId": "ukgvw4i8",
            "startedByUserEmail": "bartosz@paperspace.com",
            "deploymentType": "Tensorflow Serving on K8s",
            "modelId": "mosu30xm7q8vb0p",
            "modelUrl": "s3://ps-projects-development/prmr22ve0/ehla1kvbwzaco/model/",
            "name": "some_name",
            "tag": None,
            "params": None,
            "code": None,
            "cluster": "PS Jobs on GCP",
            "machineType": "K80",
            "imageUrl": "https://github.com/Paperspace/mnist-sample",
            "imageUsername": None,
            "imagePassword": None,
            "workspaceUrl": None,
            "workspaceUsername": None,
            "workspacePassword": None,
            "instanceCount": 1,
            "runningCount": 0,
            "error": None,
            "authToken": "-----",
            "annotations": {},
            "oauthKey": "-----",
            "oauthSecret": "-----",
            "serviceType": "model",
            "apiType": "REST",
            "endpoint": "https://development-services.paperspace.io/model-serving/desfnnrqt1v633v:predict",
            "ports": None,
            "dtCreated": "2019-04-04T10:27:10.180Z",
            "dtModified": "2019-04-04T10:27:10.248Z",
            "dtBuildStarted": None,
            "dtBuildFinished": None,
            "dtProvisioningStarted": None,
            "dtProvisioningFinished": None,
            "dtStarted": None,
            "dtTeardownStarted": None,
            "dtTeardownFinished": None,
            "dtStopped": "2019-04-04T10:27:10.230Z",
            "dtDeleted": None,
            "isDeleted": False
        },
        {
            "id": "desdyn55d2e02su",
            "ownerId": "tejxgn5bt",
            "projectId": "prmr22ve0",
            "experimentId": "ehla1kvbwzaco",
            "state": "Stopped",
            "startedByUserId": "ukgvw4i8",
            "startedByUserEmail": "bartosz@paperspace.com",
            "deploymentType": "Tensorflow Serving on K8s",
            "modelId": "mosu30xm7q8vb0p",
            "modelUrl": "s3://ps-projects-development/prmr22ve0/ehla1kvbwzaco/model/",
            "name": "some_name",
            "tag": None,
            "params": None,
            "code": None,
            "cluster": "PS Jobs on GCP",
            "machineType": "K80",
            "imageUrl": "https://github.com/Paperspace/mnist-sample",
            "imageUsername": None,
            "imagePassword": None,
            "workspaceUrl": None,
            "workspaceUsername": None,
            "workspacePassword": None,
            "instanceCount": 1,
            "runningCount": 0,
            "error": None,
            "authToken": "-----",
            "annotations": {},
            "oauthKey": "-----",
            "oauthSecret": "-----",
            "serviceType": "model",
            "apiType": "REST",
            "endpoint": "https://development-services.paperspace.io/model-serving/desdyn55d2e02su:predict",
            "ports": None,
            "dtCreated": "2019-04-04T10:11:10.204Z",
            "dtModified": "2019-04-04T10:11:10.281Z",
            "dtBuildStarted": None,
            "dtBuildFinished": None,
            "dtProvisioningStarted": None,
            "dtProvisioningFinished": None,
            "dtStarted": None,
            "dtTeardownStarted": None,
            "dtTeardownFinished": None,
            "dtStopped": "2019-04-04T10:11:10.260Z",
            "dtDeleted": None,
            "isDeleted": False
        },
        {
            "id": "des3tmqa3s627o9",
            "ownerId": "tejxgn5bt",
            "projectId": "prmr22ve0",
            "experimentId": "ehla1kvbwzaco",
            "state": "Stopped",
            "startedByUserId": "ukgvw4i8",
            "startedByUserEmail": "bartosz@paperspace.com",
            "deploymentType": "Tensorflow Serving on K8s",
            "modelId": "mosu30xm7q8vb0p",
            "modelUrl": "s3://ps-projects-development/prmr22ve0/ehla1kvbwzaco/model/",
            "name": "some_name",
            "tag": None,
            "params": None,
            "code": None,
            "cluster": "PS Jobs on GCP",
            "machineType": "K80",
            "imageUrl": "https://github.com/Paperspace/mnist-sample",
            "imageUsername": None,
            "imagePassword": None,
            "workspaceUrl": None,
            "workspaceUsername": None,
            "workspacePassword": None,
            "instanceCount": 1,
            "runningCount": 0,
            "error": None,
            "authToken": "-----",
            "annotations": {},
            "oauthKey": "-----",
            "oauthSecret": "-----",
            "serviceType": "model",
            "apiType": "REST",
            "endpoint": "https://development-services.paperspace.io/model-serving/des3tmqa3s627o9:predict",
            "ports": None,
            "dtCreated": "2019-04-04T09:29:22.277Z",
            "dtModified": "2019-04-04T09:29:22.345Z",
            "dtBuildStarted": None,
            "dtBuildFinished": None,
            "dtProvisioningStarted": None,
            "dtProvisioningFinished": None,
            "dtStarted": None,
            "dtTeardownStarted": None,
            "dtTeardownFinished": None,
            "dtStopped": "2019-04-04T09:29:22.327Z",
            "dtDeleted": None,
            "isDeleted": False
        }
    ],
    "total": 5,
    "displayTotal": 5,
    "runningTotal": 0
}

CREATE_MACHINE_RESPONSE = {
    "id": "psclbvqpc",
    "name": "some_machine",
    "os": None,
    "ram": None,
    "cpus": 1,
    "gpu": None,
    "storageTotal": None,
    "storageUsed": None,
    "usageRate": "Pro hourly",
    "shutdownTimeoutInHours": 168,
    "shutdownTimeoutForces": False,
    "performAutoSnapshot": False,
    "autoSnapshotFrequency": None,
    "autoSnapshotSaveCount": None,
    "dynamicPublicIp": False,
    "agentType": "WindowsDesktop",
    "dtCreated": "2019-04-10T14:19:49.852Z",
    "state": "provisioning",
    "updatesPending": False,
    "networkId": None,
    "privateIpAddress": None,
    "publicIpAddress": None,
    "region": None,
    "userId": "u3z4be26",
    "teamId": "te6hh34n6",
    "scriptId": None,
    "dtLastRun": None
}

LIST_MACHINES_RESPONSE = [
    {
        "ram": None,
        "userId": "u3z4be26",
        "cpus": 1,
        "teamId": "te6hh34n6",
        "updatesPending": False,
        "dynamicPublicIp": False,
        "storageTotal": None,
        "shutdownTimeoutForces": False,
        "id": "psclbvqpc",
        "shutdownTimeoutInHours": 168,
        "state": "provisioning",
        "usageRate": "Pro hourly",
        "publicIpAddress": None,
        "gp": None,
        "privateIpAddress": None,
        "dtCreated": "2019-04-10T14:19:49.852Z",
        "dtLastRun": None,
        "storageUsed": None,
        "scriptId": None,
        "autoSnapshotSaveCount": None,
        "name": "keton2",
        "agentType": "WindowsDesktop",
        "performAutoSnapshot": False,
        "networkId": None,
        "autoSnapshotFrequency": None,
        "os": None, "region": None
    },
    {
        "ram": "536870912",
        "userId": "u3z4be26",
        "cpus": 1,
        "teamId": "te6hh34n6",
        "updatesPending": False,
        "dynamicPublicIp": False,
        "storageTotal": "53687091200",
        "shutdownTimeoutForces": False,
        "id": "psbtuwfvt",
        "shutdownTimeoutInHours": 1,
        "state": "off",
        "usageRate": "C1 Hourly",
        "publicIpAddress": None,
        "gp": "None",
        "privateIpAddress": "10.64.14.135",
        "dtCreated": "2019-04-11T18:10:29.665Z",
        "dtLastRun": None,
        "storageUsed": "110080",
        "scriptId": None,
        "autoSnapshotSaveCount": 1,
        "name": "New Machine 1",
        "agentType": "LinuxHeadless",
        "performAutoSnapshot": True,
        "networkId": "nng82wb",
        "autoSnapshotFrequency": "month",
        "os": "Ubuntu 18.04.1 LTS; uname: 4.15.0-38-generic; distro: ubuntu; major: 18; minor: 04",
        "region": "East Coast (NY2)"
    }
]

SHOW_MACHINE_RESPONSE = {
    "id": "psbtuwfvt",
    "name": "New Machine 1",
    "os": "Ubuntu 18.04.1 LTS; uname: 4.15.0-38-generic; distro: ubuntu; major: 18; minor: 04",
    "ram": "536870912",
    "cpus": 1,
    "gpu": "None",
    "storageTotal": "53687091200",
    "storageUsed": "110080",
    "usageRate": "C1 Hourly",
    "shutdownTimeoutInHours": 1,
    "shutdownTimeoutForces": False,
    "performAutoSnapshot": True,
    "autoSnapshotFrequency": "month",
    "autoSnapshotSaveCount": 1,
    "dynamicPublicIp": False,
    "agentType": "LinuxHeadless",
    "dtCreated": "2019-04-11T18:10:29.665Z",
    "state": "off",
    "updatesPending": False,
    "networkId": "nng82wb",
    "privateIpAddress": "10.64.14.135",
    "publicIpAddress": None,
    "region": "East Coast (NY2)",
    "userId": "u3z4be26",
    "teamId": "te6hh34n6",
    "scriptId": None,
    "dtLastRun": None,
    "events": [
        {
            "name": "restart",
            "state": "done",
            "errorMsg": "",
            "handle": "042454c4-af4c-489a-8bff-b4d3e9f39f9e",
            "dtModified": "2019-04-12T12:19:05.801Z",
            "dtFinished": "2019-04-12T12:19:05.801Z",
            "dtCreated": "2019-04-12T12:19:03.814Z"
        },
        {
            "name": "stop",
            "state": "done",
            "errorMsg": "",
            "handle": "07fe20ce-35c4-4949-afbd-103d1afc6797",
            "dtModified": "2019-04-11T19:11:19.942Z",
            "dtFinished": "2019-04-11T19:11:19.942Z",
            "dtCreated": "2019-04-11T19:11:14.205Z"
        },
        {
            "name": "snapshot-create",
            "state": "done",
            "errorMsg": "",
            "handle": "7fa0ab4f-896d-42ac-a2c5-54f0a94c2310",
            "dtModified": "2019-04-11T18:14:36.702Z",
            "dtFinished": "2019-04-11T18:14:36.702Z",
            "dtCreated": "2019-04-11T18:14:33.216Z"
        },
        {
            "name": "start",
            "state": "done",
            "errorMsg": "",
            "handle": "c04cccdf-3823-4ef1-b1ab-83b3ccdcfcb7",
            "dtModified": "2019-04-11T18:11:00.371Z",
            "dtFinished": "2019-04-11T18:11:00.371Z",
            "dtCreated": "2019-04-11T18:10:45.468Z"
        },
        {
            "name": "create",
            "state": "done",
            "errorMsg": "",
            "handle": "34f64d24-1161-42f0-871d-1ed03b10dfc0",
            "dtModified": "2019-04-11T18:10:45.473Z",
            "dtFinished": "2019-04-11T18:10:45.473Z",
            "dtCreated": "2019-04-11T18:10:29.665Z"
        }
    ]
}

SHOW_MACHINE_UTILIZATION_RESPONSE = {
    "machineId": "psbtuwfvt",
    "utilization": {
        "machineId": "psbtuwfvt",
        "secondsUsed": 0,
        "billingMonth": "2019-04",
        "hourlyRate": 0,
    },
    "storageUtilization": {
        "machineId": "psbtuwfvt",
        "secondsUsed": 256798.902394,
        "monthlyRate": "5.00",
        "billingMonth": "2019-04",
    },
}
