EXPERIMENT_TYPE_SINGLE_NODE_ID = 1
EXPERIMENT_TYPE_GRPC_MULTI_NODE_ID = 2
EXPERIMENT_TYPE_MPI_MULTI_NODE_ID = 3

MULTI_NODE_TYPES = (EXPERIMENT_TYPE_GRPC_MULTI_NODE_ID, EXPERIMENT_TYPE_MPI_MULTI_NODE_ID)
